# This is a config for E2B sandbox template.
# You can use template ID (1sol8bvr130gcaqtd8bt) or template name (sagent-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("sagent-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("sagent-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('sagent-nextjs')

team_id = "2976a27a-3aca-4f55-a6d7-0a5b5d07ae71"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "sagent-nextjs"
template_id = "1sol8bvr130gcaqtd8bt"
